language: node_js
node_js:
- lts/*
jobs:
  include:
  - stage: release
    if: branch = master
    node_js: lts/*
    script:
    - npm run build
    - mv build sergate
    - zip -r -9 sergate.zip ./sergate -x .gitignore
    - npx semantic-release
    deploy:
      provider: script
      skip_cleanup: true
      script: rsync -e "ssh -p $deploy_port" -rz --delete-after --exclude "json" --quiet $TRAVIS_BUILD_DIR/sergate/ $deploy_user@$deploy_host:/data/sites/sergate/
    before_deploy:
    - openssl aes-256-cbc -K $encrypted_58cbb43e0460_key -iv $encrypted_58cbb43e0460_iv -in deploy_key.enc -out /tmp/deploy_key -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy_key
    - ssh-add /tmp/deploy_key
    - echo "$host_key" >> $HOME/.ssh/known_hosts
